# Challenge 1 - T-test

In statistics, t-test is used to test if two data samples have a significant difference between their means. There are two types of t-test:

* **Student's t-test** (a.k.a. independent or uncorrelated t-test). This type of t-test is to compare the samples of **two independent populations** (e.g. test scores of students in two different classes). `scipy` provides the [`ttest_ind`](https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.stats.ttest_ind.html) method to conduct student's t-test.

* **Paired t-test** (a.k.a. dependent or correlated t-test). This type of t-test is to compare the samples of **the same population** (e.g. scores of different tests of students in the same class). `scipy` provides the [`ttest_re`](https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.stats.ttest_rel.html) method to conduct paired t-test.

Both types of t-tests return a number which is called the **p-value**. If p-value is below 0.05, we can confidently declare the null-hypothesis is rejected and the difference is significant. If p-value is between 0.05 and 0.1, we may also declare the null-hypothesis is rejected but we are not highly confident. If p-value is above 0.1 we do not reject the null-hypothesis.

Read more about the t-test in [this article](https://researchbasics.education.uconn.edu/t-test/) and [this Quora](https://www.quora.com/What-is-the-difference-between-a-paired-and-unpaired-t-test). Make sure you understand when to use which type of t-test.

In [7]:
# Import libraries

import pandas as pd
import statsmodels.api as sm
from statsmodels.formula.api import ols
from scipy.stats import ttest_rel, ttest_ind
from statsmodels.stats import weightstats as w

#### Import dataset

In this challenge we will work on the Pokemon dataset you have used last week. The goal is to test whether different groups of pokemon (e.g. Legendary vs Normal, Generation 1 vs 2, single-type vs dual-type) have different stats (e.g. HP, Attack, Defense, etc.).

In [2]:
# Import dataset

pokemon = pd.read_csv('../../lab-df-calculation-and-transformation/your-code/Pokemon.csv')

pokemon.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

#### First we want to define a function with which we can test the means of a feature set of two samples. 

In the next cell you'll see the annotations of the Python function that explains what this function does and its arguments and returned value. This type of annotation is called **docstring** which is a convention used among Python developers. The docstring convention allows developers to write consistent tech documentations for their codes so that others can read. It also allows some websites to automatically parse the docstrings and display user-friendly documentations.

Follow the specifications of the docstring and complete the function.

In [28]:
def t_test_features(s1, s2, features=['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed', 'Total']):
    """Test means of a feature set of two samples
    
    Args:
        s1 (dataframe): sample 1
        s2 (dataframe): sample 2
        features (list): an array of features to test
    
    Returns:
        dict: a dictionary of t-test scores for each feature where the feature name is the key and the p-value is the value
    """
    lst = []
    for e in range(len(features)):
        z_score, p_value=w.ztest(s1[features[e]], s2[features[e]], value=0, alternative='two-sided')
        lst.append([s1[features[e]],p_value])
    
    return lst

In [11]:
#legendarios = pokemon[pokemon['Legendary']==True]
#normales = pokemon[pokemon['Legendary']==False]
#z_score, p_value=w.ztest(legendarios.HP, normales.HP, value=0, alternative='two-sided')

#### Using the `t_test_features` function, conduct t-test for Lengendary vs non-Legendary pokemons.

*Hint: your output should look like below:*

```
{'HP': 1.0026911708035284e-13,
 'Attack': 2.520372449236646e-16,
 'Defense': 4.8269984949193316e-11,
 'Sp. Atk': 1.5514614112239812e-21,
 'Sp. Def': 2.2949327864052826e-15,
 'Speed': 1.049016311882451e-18,
 'Total': 9.357954335957446e-47}
 ```

In [29]:
# Your code here
t_test_features(legendarios, normales)

[[156     90
  157     90
  158     90
  162    106
  163    106
  164    106
  262     90
  263    115
  264    100
  269    106
  270    106
  414     80
  415     80
  416     80
  417     80
  418     80
  419     80
  420     80
  421    100
  422    100
  423    100
  424    100
  425    105
  426    105
  427    100
  428     50
  429     50
  430     50
  431     50
  537     75
        ...
  543    110
  544    150
  545    150
  549     70
  550    100
  551    100
  552    120
  553    100
  699     91
  700     91
  701     91
  702     79
  703     79
  704     79
  705     79
  706    100
  707    100
  708     89
  709     89
  710    125
  711    125
  712    125
  792    126
  793    126
  794    108
  795     50
  796     50
  797     80
  798     80
  799     80
  Name: HP, Length: 65, dtype: int64, 9.27246032914108e-16], [156     85
  157     90
  158    100
  162    110
  163    190
  164    150
  262     85
  263    115
  264     75
  269     90
  270    130
  414    100
  415     50
  416     75
  417     80
  418    100
  419     90
  420    130
  421    100
  422    150
  423    150
  424    180
  425    150
  426    180
  427    100
  428    150
  429    180
  430     70
  431     95
  537     75
        ...
  543    160
  544    100
  545    120
  549     90
  550    100
  551    103
  552    120
  553    100
  699     90
  700    129
  701     90
  702    115
  703    100
  704    115
  705    105
  706    120
  707    150
  708    125
  709    145
  710    130
  711    170
  712    120
  792    131
  793    131
  794    100
  795    100
  796    160
  797    110
  798    160
  799    110
  Name: Attack, Length: 65, dtype: int64, 2.550016898775468e-25], [156    100
  157     85
  158     90
  162     90
  163    100
  164     70
  262     75
  263     85
  264    115
  269    130
  270     90
  414    200
  415    100
  416    150
  417     90
  418    120
  419     80
  420    100
  421     90
  422     90
  423    140
  424    160
  425     90
  426    100
  427    100
  428     50
  429     20
  430    160
  431     90
  537    130
        ...
  543    110
  544    120
  545    100
  549     90
  550    100
  551     75
  552    120
  553    100
  699    129
  700     90
  701     72
  702     70
  703     80
  704     70
  705     70
  706    100
  707    120
  708     90
  709     90
  710     90
  711    100
  712     90
  792     95
  793     95
  794    121
  795    150
  796    110
  797     60
  798     60
  799    120
  Name: Defense, Length: 65, dtype: int64, 6.908189648415323e-13], [156     95
  157    125
  158    125
  162    154
  163    154
  164    194
  262    115
  263     90
  264     90
  269     90
  270    110
  414     50
  415    100
  416     75
  417    110
  418    140
  419    130
  420    160
  421    150
  422    180
  423    100
  424    150
  425    150
  426    180
  427    100
  428    150
  429    180
  430     70
  431     95
  537     75
        ...
  543     80
  544    100
  545    120
  549    135
  550    100
  551    120
  552    120
  553    100
  699     90
  700     72
  701     90
  702    125
  703    110
  704    125
  705    145
  706    150
  707    120
  708    115
  709    105
  710    130
  711    120
  712    170
  792    131
  793    131
  794     81
  795    100
  796    160
  797    150
  798    170
  799    130
  Name: Sp. Atk, Length: 65, dtype: int64, 1.0356103497853376e-45], [156    125
  157     90
  158     85
  162     90
  163    100
  164    120
  262    100
  263     75
  264    115
  269    154
  270    154
  414    100
  415    200
  416    150
  417    130
  418    150
  419    110
  420    120
  421    140
  422    160
  423     90
  424     90
  425     90
  426    100
  427    100
  428     50
  429     20
  430    160
  431     90
  537    130
        ...
  543    110
  544    120
  545    100
  549     90
  550    100
  551     75
  552    120
  553    100
  699     72
  700     90
  701    129
  702     80
  703     90
  704     80
  705     80
  706    120
  707    100
  708     80
  709     80
  710     90
  711     90
  712    100
  792     98
  793     98
  794     95
  795    150
  796    110
  797    130
  798    130
  799     90
  Name: Sp. Def, Length: 65, dtype: int64, 2.512428082020712e-28], [156     85
  157    100
  158     90
  162    130
  163    130
  164    140
  262    115
  263    100
  264     85
  269    110
  270     90
  414     50
  415     50
  416     50
  417    110
  418    110
  419    110
  420    110
  421     90
  422     90
  423     90
  424     90
  425     95
  426    115
  427    100
  428    150
  429    150
  430     90
  431    180
  537     95
        ...
  543    100
  544     90
  545     90
  549    125
  550    100
  551    127
  552    120
  553    100
  699    108
  700    108
  701    108
  702    111
  703    121
  704    111
  705    101
  706     90
  707     90
  708    101
  709     91
  710     95
  711     95
  712     95
  792     99
  793     99
  794     95
  795     50
  796    110
  797     70
  798     80
  799     70
  Name: Speed, Length: 65, dtype: int64, 1.5874459879670213e-22], [156    580
  157    580
  158    580
  162    680
  163    780
  164    780
  262    580
  263    580
  264    580
  269    680
  270    680
  414    580
  415    580
  416    580
  417    600
  418    700
  419    600
  420    700
  421    670
  422    770
  423    670
  424    770
  425    680
  426    780
  427    600
  428    600
  429    600
  430    600
  431    600
  537    580
        ...
  543    670
  544    680
  545    680
  549    600
  550    600
  551    600
  552    720
  553    600
  699    580
  700    580
  701    580
  702    580
  703    580
  704    580
  705    580
  706    680
  707    680
  708    600
  709    600
  710    660
  711    700
  712    700
  792    680
  793    680
  794    600
  795    600
  796    700
  797    600
  798    680
  799    600
  Name: Total, Length: 65, dtype: int64, 2.4031368278343178e-60]]

#### From the test results above, what conclusion can you make? Do Legendary and non-Legendary pokemons have significantly different stats on each feature?

In [ ]:
# Your comment here

#### Next, conduct t-test for Generation 1 and Generation 2 pokemons.

In [ ]:
# Your code here

#### What conclusions can you make?

In [ ]:
# Your comment here

#### Compare pokemons who have single type vs those having two types.

In [ ]:
# Your code here

#### What conclusions can you make?

In [ ]:
# Your comment here

#### Now, we want to compare whether there are significant differences of `Attack` vs `Defense`  and  `Sp. Atk` vs `Sp. Def` of all pokemons. Please write your code below.

*Hint: are you comparing different populations or the same population?*

In [ ]:
# Your code here

#### What conclusions can you make?

In [ ]:
# Your comment here